# Experiment 1 — Pandas from Scratch
**NLP Lab (COMP-441L) | Task 02**

This notebook assumes you know **nothing** about Pandas yet. We will build up from zero, one small idea at a time, and finish with the official Task 02 exercises.

**How to use this notebook**
- Run each cell in order the first time, using **Shift + Enter**.
- Every cell prints its own output, so you always see what changed.
- Don't worry about memorizing anything — you can always scroll back up.

---
# Part A: Why Pandas?

NumPy is great for numbers, but real-world data usually looks like a **table** — rows and columns, with column names, and often a mix of text and numbers together (like a student's Name **and** their Score).

**Pandas** is a Python library built for exactly this. It works like a spreadsheet or a small database, inside Python.

Its main object is called a **DataFrame**.

In [2]:
import pandas as pd

print("Pandas is ready! Version:", pd.__version__)

Pandas is ready! Version: 3.0.0

---
# Part B: Loading Data into a DataFrame

`pandas.read_csv("file.csv")` reads a CSV file and gives you back a DataFrame.

In your lab, you will be given a dataset file to load. For this notebook, we will first create a small sample dataset ourselves and save it as a CSV, so you can practise the exact same commands you'll use on the real dataset.

In [3]:
import pandas as pd

# Creating a small sample dataset of students
sample_data = {
    "Name":       ["Ayesha", "Akbar", "Sana", "Usman", "Hina", "Ali", "Mehak", "Zain", "Jamal"],
    "Age":        [21, 22, 25, 23, 21, 32, 20, 24, 19],
    "Score":      [88, 74, 91, 67, 95, 58, 82, 76, 99],
    "Department": ["Computer Science", "Software Eng.", "Computer Science",
                    "Data Science", "Computer Science", "Software Eng.",
                    "Data Science", "Computer Science", "AI"],
    "Gender": ["f","m","f","m","f","m","f","m","m"]
}

df_sample = pd.DataFrame(sample_data)
df_sample.to_csv("students.csv", index=False)

print("Sample dataset saved as students.csv")
df_sample

Sample dataset saved as students.csv

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58     Software Eng.      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

**Purpose:** Clean and prepare raw text for analysis — that step comes later. Right now, let's just load this CSV the same way you will load your real dataset.

In [4]:
import pandas as pd

df = pd.read_csv("students.csv")
df

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58     Software Eng.      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

In [5]:
df_1 = pd.read_csv("students.csv")
df_1

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58     Software Eng.      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

---
# Part C: Viewing and Exploring a DataFrame

Once data is loaded, the first thing to do is **look at it**. Pandas gives us a few quick tools:
- `.head()` → shows the first 5 rows
- `.shape` → shows `(number of rows, number of columns)`
- `.columns` → shows the column names
- `.describe()` → shows summary statistics (count, mean, min, max, etc.) for numeric columns

In [6]:
import pandas as pd

df = pd.read_csv("students.csv")

print("First 5 rows:")
print(df.head())

First 5 rows:
     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f

In [7]:
import pandas as pd

df = pd.read_csv("students.csv")

print("Shape (rows, columns):", df.shape)

Shape (rows, columns): (9, 5)

In [8]:
import pandas as pd

df = pd.read_csv("students.csv")

print("Column names:", list(df.columns))
print("Indexes:", list(df.index))

Column names: ['Name', 'Age', 'Score', 'Department', 'Gender']
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
df[['Age', 'Department']]

   Age        Department
0   21  Computer Science
1   22     Software Eng.
2   25  Computer Science
3   23      Data Science
4   21  Computer Science
5   32     Software Eng.
6   20      Data Science
7   24  Computer Science
8   19                AI

In [10]:
import pandas as pd

df = pd.read_csv("students.csv")

df.describe()

             Age      Score
count   9.000000   9.000000
mean   23.000000  81.111111
std     3.872983  13.550318
min    19.000000  58.000000
25%    21.000000  74.000000
50%    22.000000  82.000000
75%    24.000000  91.000000
max    32.000000  99.000000

---
# Part D: Handling Missing Data

Real datasets often have missing values (empty cells). Pandas shows these as `NaN` (Not a Number).

`df.fillna(value)` replaces every missing value with the value you give it.

In [11]:
import pandas as pd
import numpy as np

# Let's make a small copy with a missing value, just to see how this works
df_demo = pd.read_csv("students.csv").copy()
df_demo.loc[5, "Department"] = np.nan   # pretend Sana's score wasn't recorded

print("Before fillna (notice the NaN):")
print(df_demo)

df_demo_filled = df_demo.fillna("Yet Not Decided")
print("\nAfter fillna(0):")
print(df_demo_filled)

Before fillna (notice the NaN):
     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58               NaN      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

After fillna(0):
     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58   Yet Not Decided      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

---
# Part E: Selecting and Filtering

### Selecting specific columns
Use double square brackets with the column names you want: `df[["Col1", "Col2"]]`

### Filtering rows by a condition
Write a condition inside square brackets, e.g. `df[df["Score"] > 80]`. Pandas keeps only the rows where the condition is `True`.

In [12]:
import pandas as pd

df = pd.read_csv("students.csv")

# Selecting only the Name and Score columns
df[["Name", "Score"]]

     Name  Score
0  Ayesha     88
1   Akbar     74
2    Sana     91
3   Usman     67
4    Hina     95
5     Ali     58
6   Mehak     82
7    Zain     76
8   Jamal     99

In [13]:
import pandas as pd

df = pd.read_csv("students.csv")

# Filtering: keep only students with Score > 80
df[df["Age"] > 23]

   Name  Age  Score        Department Gender
2  Sana   25     91  Computer Science      f
5   Ali   32     58     Software Eng.      m
7  Zain   24     76  Computer Science      m

In [14]:
import pandas as pd

df = pd.read_csv("students.csv")

# Filtering: keep only students in the Computer Science department
df[df["Department"] == "Data Science"]

    Name  Age  Score    Department Gender
3  Usman   23     67  Data Science      m
6  Mehak   20     82  Data Science      f

In [15]:
# Filtering: Based on Names
df[df["Name"] == "Zain"]

   Name  Age  Score        Department Gender
7  Zain   24     76  Computer Science      m

---
# Part F: Adding and Removing Columns

Adding a new column is as simple as assigning it a value, often computed from other columns.

Removing a column uses `.drop(columns=["ColumnName"])`.

In [16]:
import pandas as pd

df = pd.read_csv("students.csv")

# Adding a new column: Pass/Fail based on Score
df["Result"] = df["Score"].apply(lambda s: "Pass" if s >= 60 else "Fail")
df

     Name  Age  Score        Department Gender Result
0  Ayesha   21     88  Computer Science      f   Pass
1   Akbar   22     74     Software Eng.      m   Pass
2    Sana   25     91  Computer Science      f   Pass
3   Usman   23     67      Data Science      m   Pass
4    Hina   21     95  Computer Science      f   Pass
5     Ali   32     58     Software Eng.      m   Fail
6   Mehak   20     82      Data Science      f   Pass
7    Zain   24     76  Computer Science      m   Pass
8   Jamal   19     99                AI      m   Pass

In [17]:
import pandas as pd

df = pd.read_csv("students.csv")
df["Result"] = df["Score"].apply(lambda s: "Pass" if s >= 60 else "Fail")

# Removing the Result column again
df_dropped = df.drop(columns=["Result"])
df_dropped

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f
5     Ali   32     58     Software Eng.      m
6   Mehak   20     82      Data Science      f
7    Zain   24     76  Computer Science      m
8   Jamal   19     99                AI      m

---
# 🎉 You now know everything needed for Task 02!

Quick recap:
| What we learned | Pandas tool |
|---|---|
| Loading data | `pd.read_csv()` |
| Viewing/exploring | `.head()`, `.shape`, `.columns`, `.describe()` |
| Handling missing data | `.fillna()` |
| Selecting columns | `df[["Col1", "Col2"]]` |
| Filtering rows | `df[df["Col"] > value]` |
| Adding/removing columns | `df["New"] = ...`, `.drop(columns=[...])` |

Now let's do the official Task 02, step by step. Each task below is its own cell — run them one at a time and check the output.

*(We will keep using `students.csv`, the sample dataset created in Part B. In your real lab, replace `"students.csv"` with the filename of the dataset you were given.)*

---
# Task 02 — Official Lab Exercises
## Task 2.1: Load the dataset into a DataFrame

In [18]:
import pandas as pd
dframe = pd.read_csv("students.csv")

## Task 2.2: Display the first 5 rows, the shape, and the column names

In [19]:
import pandas as pd
print(dframe.head())

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
1   Akbar   22     74     Software Eng.      m
2    Sana   25     91  Computer Science      f
3   Usman   23     67      Data Science      m
4    Hina   21     95  Computer Science      f

## Task 2.3: Select the Name and Score columns

In [20]:
import pandas as pd
dframe[["Name","Score"]]

     Name  Score
0  Ayesha     88
1   Akbar     74
2    Sana     91
3   Usman     67
4    Hina     95
5     Ali     58
6   Mehak     82
7    Zain     76
8   Jamal     99

## Task 2.4: Get summary statistics with describe()

In [21]:
import pandas as pd
dframe.describe()

             Age      Score
count   9.000000   9.000000
mean   23.000000  81.111111
std     3.872983  13.550318
min    19.000000  58.000000
25%    21.000000  74.000000
50%    22.000000  82.000000
75%    24.000000  91.000000
max    32.000000  99.000000

## Task 2.5: Find the average age of the students

In [22]:
import pandas as pd
avg_age= dframe['Age'].mean()
print("Average Age: ", avg_age)

Average Age:  23.0

## Task 2.6: Filter students with Score > 80

In [23]:
import pandas as pd
dframe[dframe['Score']>80]

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
2    Sana   25     91  Computer Science      f
4    Hina   21     95  Computer Science      f
6   Mehak   20     82      Data Science      f
8   Jamal   19     99                AI      m

## Task 2.7: Filter students in the Computer Science department

In [24]:
import pandas as pd
dframe[dframe['Department']=="Computer Science"]

     Name  Age  Score        Department Gender
0  Ayesha   21     88  Computer Science      f
2    Sana   25     91  Computer Science      f
4    Hina   21     95  Computer Science      f
7    Zain   24     76  Computer Science      m

---
## ✅ Task 02 complete!

You've learned: loading data, viewing and exploring a DataFrame, handling missing data, selecting columns, filtering rows, and adding/removing columns.

**Show your outputs to the instructor for sign-off, then move on to Task 03 (Matplotlib and Seaborn).**

Github link: